version: "3"

services:

  postgres-service:
    container_name: postgres-service
    image: postgres:16.2
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env


  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: "no"
    ports:
      - "5050:80"
    env_file:
      - .env

  elasticsearch:
    image: elasticsearch:8.15.0
    container_name: elasticsearch
    restart: always
    env_file:
      - .env
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elastic

  kibana:
    image: kibana:8.15.0
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elastic

networks:
  elastic:
    driver: bridge