# API GATEWAY PROPERTIES
server:
  port: 9191

# EUREKA
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka

# ACTUATOR
management:
  tracing:
    sampling:
      probability: 1.0
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    health:
      show-details: always
      show-components: always
  endpoints:
    web:
      exposure:
        exclude: "*"
      cors:
        allowed-methods: GET,POST
  prometheus:
    metrics:
      export:
        enabled: true

# Jwt Key
jwt:
  secret:
    key: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

spring:
  application:
    name: api-gateway-service
  cloud:
    discovery:
      enabled: true
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - OPTIONS
              - PUT
              - PATCH
              - HEAD
              - DELETE
      routes:

          # user-service user controller
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
          filters:
            - AuthFilter=ADMIN

        # user-service auth controller
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/auth/**

        # user-service role controller
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/roles/**
          filters:
            - AuthFilter=ADMIN

        # search-service user search controller
        - id: SEARCH-SERVICE
          uri: lb://SEARCH-SERVICE
          predicates:
            - Path=/api/v1/search/users/**
          filters:
            - AuthFilter=ADMIN