resilience4j:
  circuitbreaker:
    instances:
      getUserStringCircuitBreaker:
        sliding-window-type: count_based
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state:
          seconds: 50
        failure-rate-threshold: 50
        register-health-indicator: true
        event-consumer-buffer-size: 10
        automatic-transition-from-open-to-half-open-enabled: true
        recordFailurePredicate: io.github.robwin.exception.RecordFailurePredicate
