spring.application.name=search-service
spring.profiles.active=@activatedProperties@
springdoc.swagger-ui.path=/api
server.port=8082

# EUREKA
eureka.client.service-url.defaultZone=http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka
eureka.instance.prefer-ip-address=true
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true

# ACTUATOR
management.tracing.sampling.probability=1.0
management.metrics.tags.application=${spring.application.name}
management.endpoint.health.show-details=always
management.endpoint.health.show-components=always
management.endpoints.web.exposure.include=*
management.prometheus.metrics.export.enabled=true
management.endpoints.web.cors.allowed-methods=GET,POST