version: "3"

services:

  postgres-service:
    container_name: postgres-service
    image: postgres:16.2
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./postgre-config:/postgre-config
    command: postgres -c config_file=/postgre-config/postgresql.conf
    networks:
      - elastic

  elasticsearch:
    image: elasticsearch:8.16.2
    container_name: elasticsearch
    env_file:
      - .env
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - elastic

  kibana:
    image: kibana:8.16.2
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
      xpack.encryptedSavedObjects.encryptionKey: "12345678901234567890123456789012"
    volumes:
      - ./data/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on:
      - elasticsearch
    networks:
      - elastic

  elastalert:
    image: jertel/elastalert2
    container_name: elastalert
    volumes:
      - ./data/elastalert/config:/opt/elastalert/config
      - ./data/elastalert/rules:/opt/elastalert/rules
    command: --verbose
    depends_on:
      - elasticsearch
    networks:
      - elastic

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.6.0
    restart: always
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - elastic

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.6.0
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_MESSAGE_MAX_BYTES: 15728640 # set message.max.bytes to 15MB
      KAFKA_MAX_REQUEST_SIZE: 15728640 # set max.request.size to 15MB
      KAFKA_ADVERTISED_HOST_NAME:
    networks:
      - elastic

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "9093:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=localhost:2181
    networks:
      - elastic

  debezium:
    image: debezium/connect:1.5
    ports:
      - "8089:8083"
    environment:
      - BOOTSTRAP_SERVERS=kafka:29092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=debezium-connect-configs
      - OFFSET_STORAGE_TOPIC=debezium-connect-offsets
      - STATUS_STORAGE_TOPIC=debezium-connect-statuses
    networks:
      - elastic
    volumes:
      - debezium-volume:/kafka/data

  debezium-ui:
    image: debezium/debezium-ui:2.4
    platform: linux/amd64
    env_file:
      - .env
    ports:
      - "9091:8080"
    depends_on:
      - debezium
    networks:
      - elastic

  kafka-connect:
    image: confluentinc/cp-kafka-connect:5.4.9
    restart: always
    container_name: kafka-connect
    ports:
      - '8070:8083'
    depends_on:
      - zookeeper
      - kafka
      - elasticsearch
    volumes:
      - ./connect-plugins:/connect-plugins
      - kafka-connect-volume:/kafka/data
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka:29092
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: 'connect'
      CONNECT_CONFIG_STORAGE_TOPIC: elasticsearch-connect-config
      CONNECT_OFFSET_STORAGE_TOPIC: elasticsearch-connect-offsets
      CONNECT_STATUS_STORAGE_TOPIC: elasticsearch-connect-status
      CONNECT_REPLICATION_FACTOR: 1
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: 'org.apache.kafka.connect.storage.StringConverter'
      CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE: 'false'
      CONNECT_VALUE_CONVERTER: 'org.apache.kafka.connect.json.JsonConverter'
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: 'true'
      CONNECT_INTERNAL_KEY_CONVERTER: 'org.apache.kafka.connect.json.JsonConverter'
      CONNECT_INTERNAL_VALUE_CONVERTER: 'org.apache.kafka.connect.json.JsonConverter'
      CONNECT_PRODUCER_INTERCEPTOR_CLASSES: 'io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor'
      CONNECT_CONSUMER_INTERCEPTOR_CLASSES: 'io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor'
      CONNECT_REST_ADVERTISED_HOST_NAME: 'connect'
      CONNECT_ZOOKEEPER_CONNECT: zookeeper:2181
      CONNECT_PLUGIN_PATH: /connect-plugins
      CONNECT_LOG4J_ROOT_LOGLEVEL: INFO
      CONNECT_LOG4J_LOGGERS: org.reflections=ERROR
      CLASSPATH: /usr/share/java/monitoring-interceptors/monitoring-interceptors-3.3.0.jar
    networks:
      - elastic

  logstash:
    image: logstash:8.16.2
    container_name: logstash
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elastic
    depends_on:
      - elasticsearch

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./data/prometheus/config:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - elastic

  grafana:
    image: "grafana/grafana-oss:latest"
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_DOMAIN=localhost
    networks:
      - elastic

volumes:
  kafka-connect-volume:
  debezium-volume:
  elasticsearch_data:
    driver: local

networks:
  elastic:
    driver: bridge