# Jpa
spring.jpa.database=POSTGRESQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=false

# Postgresql
spring.datasource.url=jdbc:postgresql://localhost:5432/db
spring.datasource.username=root
spring.datasource.password=root

#elastic
spring.data.elasticsearch.repositories.enabled=true
spring.elasticsearch.uris=localhost:9200

# EUREKA
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

jwt.secret.key=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa