# Bu postgresql config dosyası container ayağa kalkarken wal_level seviyesini değiştirmek için kullanılır.
# Bu config dosyası manuel olarak ayarandığı için postgresql default ayarları kullanılmaz.
# Varsayılan ayarları kullanabilmek için
# include '/var/lib/postgresql/data/postgresql.conf' satırı config dosyasının başına eklenir.
include '/var/lib/postgresql/data/postgresql.conf'
wal_level = logical
max_replication_slots = 10
max_wal_senders = 10