spring.application.name=eureka-server

# App Port
server.port=8761
eureka.instance.hostname=localhost
eureka.client.registerWithEureka=false
eureka.client.fetchRegistry=false

# ACTUATOR
management.tracing.sampling.probability=1.0
management.metrics.tags.application=${spring.application.name}
management.endpoint.health.show-details=always
management.endpoint.health.show-components=always
management.endpoints.web.exposure.include=*
management.prometheus.metrics.export.enabled=true
management.endpoints.web.cors.allowed-methods=GET,POST